version: '3.8'

services:
  medical-mcp:
    build: .
    container_name: medical-ontology-mcp
    ports:
      - "8080:8080"
    volumes:
      - ./data:/app/data:ro
      - ./config:/app/config
      - ./logs:/app/logs
    environment:
      - MCP_PORT=8080
      - MCP_HOST=0.0.0.0
      - LOG_LEVEL=INFO
      - DATA_PATH=/app/data
      - CONFIG_PATH=/app/config/config.yaml
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Optional: Redis for caching (uncomment if needed)
  # redis:
  #   image: redis:7-alpine
  #   container_name: medical-mcp-cache
  #   ports:
  #     - "6379:6379"
  #   volumes:
  #     - redis-data:/data
  #   restart: unless-stopped

# volumes:
#   redis-data: